-- Insert Data into STUDENT Table
INSERT INTO STUDENT(FIRSTNAME,LASTNAME,COURSE,COUNTRY) VALUES('Suresh','Reddy','B.Tech','India');
INSERT INTO STUDENT(FIRSTNAME,LASTNAME,COURSE,COUNTRY) VALUES( 'Murali','Mohan','B.Arch','Canada');
INSERT INTO STUDENT(FIRSTNAME,LASTNAME,COURSE,COUNTRY) VALUES( 'Daniel','Denson','B.Tech','New Zealand');
INSERT INTO STUDENT(FIRSTNAME,LASTNAME,COURSE,COUNTRY) VALUES('Tanya','Gupta','B.com','USA');